-- Adaptive Strategic AI: competitive difficulty curve for Gathering Storm.
-- Vanilla Deity totals are +80% production/gold, +32% science/culture/faith,
-- +4 combat strength, and +40% unit XP. These modifiers retain a visible but
-- reduced opening lead, then ramp to a stronger late-game economy.

-- Deity receives one extra Settler, two extra Warriors, and one Builder. This
-- sits between the previous reduced start and the full vanilla Deity opening.
DELETE FROM MajorStartingUnits
WHERE Era = 'ERA_ANCIENT'
  AND AiOnly = 1
  AND Unit IN ('UNIT_SETTLER', 'UNIT_WARRIOR', 'UNIT_BUILDER');

INSERT INTO MajorStartingUnits
    (Unit, Era, Quantity, NotStartTile, OnDistrictCreated, AiOnly,
     MinDifficulty, DifficultyDelta)
VALUES
    ('UNIT_SETTLER', 'ERA_ANCIENT', 1, 0, 1, 1, 'DIFFICULTY_DEITY', 0),
    ('UNIT_WARRIOR', 'ERA_ANCIENT', 1, 1, 0, 1, 'DIFFICULTY_KING', 0),
    ('UNIT_WARRIOR', 'ERA_ANCIENT', 1, 1, 0, 1, 'DIFFICULTY_DEITY', 0),
    ('UNIT_BUILDER', 'ERA_ANCIENT', 1, 0, 1, 1, 'DIFFICULTY_EMPEROR', 0);

INSERT OR IGNORE INTO Requirements
    (RequirementId, RequirementType, Inverse)
VALUES
    ('ASAI_REQUIRES_AI', 'REQUIREMENT_PLAYER_IS_HUMAN', 1),
    ('ASAI_REQUIRES_DEITY', 'REQUIREMENT_PLAYER_HANDICAP_AT_OR_ABOVE', 0),
    ('ASAI_REQUIRES_WORLD_CLASSICAL', 'REQUIREMENT_GAME_ERA_ATLEAST_EXPANSION', 0),
    ('ASAI_REQUIRES_WORLD_MEDIEVAL', 'REQUIREMENT_GAME_ERA_ATLEAST_EXPANSION', 0),
    ('ASAI_REQUIRES_WORLD_RENAISSANCE', 'REQUIREMENT_GAME_ERA_ATLEAST_EXPANSION', 0),
    ('ASAI_REQUIRES_WORLD_INDUSTRIAL', 'REQUIREMENT_GAME_ERA_ATLEAST_EXPANSION', 0),
    ('ASAI_REQUIRES_WORLD_MODERN', 'REQUIREMENT_GAME_ERA_ATLEAST_EXPANSION', 0),
    ('ASAI_REQUIRES_WORLD_ATOMIC', 'REQUIREMENT_GAME_ERA_ATLEAST_EXPANSION', 0),
    ('ASAI_REQUIRES_WORLD_INFORMATION', 'REQUIREMENT_GAME_ERA_ATLEAST_EXPANSION', 0);

INSERT OR IGNORE INTO RequirementArguments
    (RequirementId, Name, Value)
VALUES
    ('ASAI_REQUIRES_DEITY', 'Handicap', 'DIFFICULTY_DEITY'),
    ('ASAI_REQUIRES_WORLD_CLASSICAL', 'EraType', 'ERA_CLASSICAL'),
    ('ASAI_REQUIRES_WORLD_MEDIEVAL', 'EraType', 'ERA_MEDIEVAL'),
    ('ASAI_REQUIRES_WORLD_RENAISSANCE', 'EraType', 'ERA_RENAISSANCE'),
    ('ASAI_REQUIRES_WORLD_INDUSTRIAL', 'EraType', 'ERA_INDUSTRIAL'),
    ('ASAI_REQUIRES_WORLD_MODERN', 'EraType', 'ERA_MODERN'),
    ('ASAI_REQUIRES_WORLD_ATOMIC', 'EraType', 'ERA_ATOMIC'),
    ('ASAI_REQUIRES_WORLD_INFORMATION', 'EraType', 'ERA_INFORMATION');

INSERT OR IGNORE INTO RequirementSets
    (RequirementSetId, RequirementSetType)
VALUES
    ('ASAI_DEITY_AI', 'REQUIREMENTSET_TEST_ALL'),
    ('ASAI_DEITY_AI_CLASSICAL', 'REQUIREMENTSET_TEST_ALL'),
    ('ASAI_DEITY_AI_MEDIEVAL', 'REQUIREMENTSET_TEST_ALL'),
    ('ASAI_DEITY_AI_RENAISSANCE', 'REQUIREMENTSET_TEST_ALL'),
    ('ASAI_DEITY_AI_INDUSTRIAL', 'REQUIREMENTSET_TEST_ALL'),
    ('ASAI_DEITY_AI_MODERN', 'REQUIREMENTSET_TEST_ALL'),
    ('ASAI_DEITY_AI_ATOMIC', 'REQUIREMENTSET_TEST_ALL'),
    ('ASAI_DEITY_AI_INFORMATION', 'REQUIREMENTSET_TEST_ALL');

INSERT OR IGNORE INTO RequirementSetRequirements
    (RequirementSetId, RequirementId)
VALUES
    ('ASAI_DEITY_AI', 'ASAI_REQUIRES_AI'),
    ('ASAI_DEITY_AI', 'ASAI_REQUIRES_DEITY'),
    ('ASAI_DEITY_AI_CLASSICAL', 'ASAI_REQUIRES_AI'),
    ('ASAI_DEITY_AI_CLASSICAL', 'ASAI_REQUIRES_DEITY'),
    ('ASAI_DEITY_AI_CLASSICAL', 'ASAI_REQUIRES_WORLD_CLASSICAL'),
    ('ASAI_DEITY_AI_MEDIEVAL', 'ASAI_REQUIRES_AI'),
    ('ASAI_DEITY_AI_MEDIEVAL', 'ASAI_REQUIRES_DEITY'),
    ('ASAI_DEITY_AI_MEDIEVAL', 'ASAI_REQUIRES_WORLD_MEDIEVAL'),
    ('ASAI_DEITY_AI_RENAISSANCE', 'ASAI_REQUIRES_AI'),
    ('ASAI_DEITY_AI_RENAISSANCE', 'ASAI_REQUIRES_DEITY'),
    ('ASAI_DEITY_AI_RENAISSANCE', 'ASAI_REQUIRES_WORLD_RENAISSANCE'),
    ('ASAI_DEITY_AI_INDUSTRIAL', 'ASAI_REQUIRES_AI'),
    ('ASAI_DEITY_AI_INDUSTRIAL', 'ASAI_REQUIRES_DEITY'),
    ('ASAI_DEITY_AI_INDUSTRIAL', 'ASAI_REQUIRES_WORLD_INDUSTRIAL'),
    ('ASAI_DEITY_AI_MODERN', 'ASAI_REQUIRES_AI'),
    ('ASAI_DEITY_AI_MODERN', 'ASAI_REQUIRES_DEITY'),
    ('ASAI_DEITY_AI_MODERN', 'ASAI_REQUIRES_WORLD_MODERN'),
    ('ASAI_DEITY_AI_ATOMIC', 'ASAI_REQUIRES_AI'),
    ('ASAI_DEITY_AI_ATOMIC', 'ASAI_REQUIRES_DEITY'),
    ('ASAI_DEITY_AI_ATOMIC', 'ASAI_REQUIRES_WORLD_ATOMIC'),
    ('ASAI_DEITY_AI_INFORMATION', 'ASAI_REQUIRES_AI'),
    ('ASAI_DEITY_AI_INFORMATION', 'ASAI_REQUIRES_DEITY'),
    ('ASAI_DEITY_AI_INFORMATION', 'ASAI_REQUIRES_WORLD_INFORMATION');

-- Yield modifiers. Each later-era modifier is incremental and cumulative.
INSERT OR IGNORE INTO Modifiers
    (ModifierId, ModifierType, OwnerRequirementSetId)
VALUES
    ('ASAI_DEITY_OPENING_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI'),
    ('ASAI_DEITY_OPENING_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI'),
    ('ASAI_DEITY_OPENING_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI'),
    ('ASAI_DEITY_OPENING_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI'),
    ('ASAI_DEITY_OPENING_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI'),
    ('ASAI_DEITY_CLASSICAL_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_CLASSICAL'),
    ('ASAI_DEITY_CLASSICAL_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_CLASSICAL'),
    ('ASAI_DEITY_CLASSICAL_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_CLASSICAL'),
    ('ASAI_DEITY_CLASSICAL_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_CLASSICAL'),
    ('ASAI_DEITY_CLASSICAL_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_CLASSICAL'),
    ('ASAI_DEITY_MEDIEVAL_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_MEDIEVAL'),
    ('ASAI_DEITY_MEDIEVAL_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_MEDIEVAL'),
    ('ASAI_DEITY_MEDIEVAL_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_MEDIEVAL'),
    ('ASAI_DEITY_MEDIEVAL_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_MEDIEVAL'),
    ('ASAI_DEITY_MEDIEVAL_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_MEDIEVAL'),
    ('ASAI_DEITY_RENAISSANCE_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_RENAISSANCE'),
    ('ASAI_DEITY_RENAISSANCE_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_RENAISSANCE'),
    ('ASAI_DEITY_RENAISSANCE_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_RENAISSANCE'),
    ('ASAI_DEITY_RENAISSANCE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_RENAISSANCE'),
    ('ASAI_DEITY_RENAISSANCE_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_RENAISSANCE'),
    ('ASAI_DEITY_INDUSTRIAL_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_INDUSTRIAL'),
    ('ASAI_DEITY_INDUSTRIAL_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_INDUSTRIAL'),
    ('ASAI_DEITY_INDUSTRIAL_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_INDUSTRIAL'),
    ('ASAI_DEITY_INDUSTRIAL_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_INDUSTRIAL'),
    ('ASAI_DEITY_INDUSTRIAL_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_INDUSTRIAL'),
    ('ASAI_DEITY_MODERN_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_MODERN'),
    ('ASAI_DEITY_MODERN_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_MODERN'),
    ('ASAI_DEITY_MODERN_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_MODERN'),
    ('ASAI_DEITY_MODERN_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_MODERN'),
    ('ASAI_DEITY_MODERN_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_MODERN'),
    ('ASAI_DEITY_ATOMIC_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_ATOMIC'),
    ('ASAI_DEITY_ATOMIC_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_ATOMIC'),
    ('ASAI_DEITY_ATOMIC_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_ATOMIC'),
    ('ASAI_DEITY_ATOMIC_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_ATOMIC'),
    ('ASAI_DEITY_ATOMIC_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_ATOMIC'),
    ('ASAI_DEITY_INFORMATION_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_INFORMATION'),
    ('ASAI_DEITY_INFORMATION_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_INFORMATION'),
    ('ASAI_DEITY_INFORMATION_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_INFORMATION'),
    ('ASAI_DEITY_INFORMATION_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_INFORMATION'),
    ('ASAI_DEITY_INFORMATION_GOLD', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'ASAI_DEITY_AI_INFORMATION');

INSERT OR REPLACE INTO ModifierArguments
    (ModifierId, Name, Value)
VALUES
    ('ASAI_DEITY_OPENING_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
    ('ASAI_DEITY_OPENING_SCIENCE', 'Amount', -8),
    ('ASAI_DEITY_OPENING_CULTURE', 'YieldType', 'YIELD_CULTURE'),
    ('ASAI_DEITY_OPENING_CULTURE', 'Amount', -8),
    ('ASAI_DEITY_OPENING_FAITH', 'YieldType', 'YIELD_FAITH'),
    ('ASAI_DEITY_OPENING_FAITH', 'Amount', -8),
    ('ASAI_DEITY_OPENING_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
    ('ASAI_DEITY_OPENING_PRODUCTION', 'Amount', -30),
    ('ASAI_DEITY_OPENING_GOLD', 'YieldType', 'YIELD_GOLD'),
    ('ASAI_DEITY_OPENING_GOLD', 'Amount', -30),
    ('ASAI_DEITY_CLASSICAL_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
    ('ASAI_DEITY_CLASSICAL_SCIENCE', 'Amount', 3),
    ('ASAI_DEITY_CLASSICAL_CULTURE', 'YieldType', 'YIELD_CULTURE'),
    ('ASAI_DEITY_CLASSICAL_CULTURE', 'Amount', 3),
    ('ASAI_DEITY_CLASSICAL_FAITH', 'YieldType', 'YIELD_FAITH'),
    ('ASAI_DEITY_CLASSICAL_FAITH', 'Amount', 3),
    ('ASAI_DEITY_CLASSICAL_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
    ('ASAI_DEITY_CLASSICAL_PRODUCTION', 'Amount', 5),
    ('ASAI_DEITY_CLASSICAL_GOLD', 'YieldType', 'YIELD_GOLD'),
    ('ASAI_DEITY_CLASSICAL_GOLD', 'Amount', 5),
    ('ASAI_DEITY_MEDIEVAL_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
    ('ASAI_DEITY_MEDIEVAL_SCIENCE', 'Amount', 5),
    ('ASAI_DEITY_MEDIEVAL_CULTURE', 'YieldType', 'YIELD_CULTURE'),
    ('ASAI_DEITY_MEDIEVAL_CULTURE', 'Amount', 5),
    ('ASAI_DEITY_MEDIEVAL_FAITH', 'YieldType', 'YIELD_FAITH'),
    ('ASAI_DEITY_MEDIEVAL_FAITH', 'Amount', 5),
    ('ASAI_DEITY_MEDIEVAL_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
    ('ASAI_DEITY_MEDIEVAL_PRODUCTION', 'Amount', 10),
    ('ASAI_DEITY_MEDIEVAL_GOLD', 'YieldType', 'YIELD_GOLD'),
    ('ASAI_DEITY_MEDIEVAL_GOLD', 'Amount', 10),
    ('ASAI_DEITY_RENAISSANCE_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
    ('ASAI_DEITY_RENAISSANCE_SCIENCE', 'Amount', 6),
    ('ASAI_DEITY_RENAISSANCE_CULTURE', 'YieldType', 'YIELD_CULTURE'),
    ('ASAI_DEITY_RENAISSANCE_CULTURE', 'Amount', 6),
    ('ASAI_DEITY_RENAISSANCE_FAITH', 'YieldType', 'YIELD_FAITH'),
    ('ASAI_DEITY_RENAISSANCE_FAITH', 'Amount', 6),
    ('ASAI_DEITY_RENAISSANCE_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
    ('ASAI_DEITY_RENAISSANCE_PRODUCTION', 'Amount', 10),
    ('ASAI_DEITY_RENAISSANCE_GOLD', 'YieldType', 'YIELD_GOLD'),
    ('ASAI_DEITY_RENAISSANCE_GOLD', 'Amount', 10),
    ('ASAI_DEITY_INDUSTRIAL_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
    ('ASAI_DEITY_INDUSTRIAL_SCIENCE', 'Amount', 7),
    ('ASAI_DEITY_INDUSTRIAL_CULTURE', 'YieldType', 'YIELD_CULTURE'),
    ('ASAI_DEITY_INDUSTRIAL_CULTURE', 'Amount', 7),
    ('ASAI_DEITY_INDUSTRIAL_FAITH', 'YieldType', 'YIELD_FAITH'),
    ('ASAI_DEITY_INDUSTRIAL_FAITH', 'Amount', 7),
    ('ASAI_DEITY_INDUSTRIAL_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
    ('ASAI_DEITY_INDUSTRIAL_PRODUCTION', 'Amount', 10),
    ('ASAI_DEITY_INDUSTRIAL_GOLD', 'YieldType', 'YIELD_GOLD'),
    ('ASAI_DEITY_INDUSTRIAL_GOLD', 'Amount', 10),
    ('ASAI_DEITY_MODERN_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
    ('ASAI_DEITY_MODERN_SCIENCE', 'Amount', 7),
    ('ASAI_DEITY_MODERN_CULTURE', 'YieldType', 'YIELD_CULTURE'),
    ('ASAI_DEITY_MODERN_CULTURE', 'Amount', 7),
    ('ASAI_DEITY_MODERN_FAITH', 'YieldType', 'YIELD_FAITH'),
    ('ASAI_DEITY_MODERN_FAITH', 'Amount', 7),
    ('ASAI_DEITY_MODERN_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
    ('ASAI_DEITY_MODERN_PRODUCTION', 'Amount', 10),
    ('ASAI_DEITY_MODERN_GOLD', 'YieldType', 'YIELD_GOLD'),
    ('ASAI_DEITY_MODERN_GOLD', 'Amount', 10),
    ('ASAI_DEITY_ATOMIC_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
    ('ASAI_DEITY_ATOMIC_SCIENCE', 'Amount', 8),
    ('ASAI_DEITY_ATOMIC_CULTURE', 'YieldType', 'YIELD_CULTURE'),
    ('ASAI_DEITY_ATOMIC_CULTURE', 'Amount', 8),
    ('ASAI_DEITY_ATOMIC_FAITH', 'YieldType', 'YIELD_FAITH'),
    ('ASAI_DEITY_ATOMIC_FAITH', 'Amount', 8),
    ('ASAI_DEITY_ATOMIC_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
    ('ASAI_DEITY_ATOMIC_PRODUCTION', 'Amount', 10),
    ('ASAI_DEITY_ATOMIC_GOLD', 'YieldType', 'YIELD_GOLD'),
    ('ASAI_DEITY_ATOMIC_GOLD', 'Amount', 10),
    ('ASAI_DEITY_INFORMATION_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
    ('ASAI_DEITY_INFORMATION_SCIENCE', 'Amount', 0),
    ('ASAI_DEITY_INFORMATION_CULTURE', 'YieldType', 'YIELD_CULTURE'),
    ('ASAI_DEITY_INFORMATION_CULTURE', 'Amount', 0),
    ('ASAI_DEITY_INFORMATION_FAITH', 'YieldType', 'YIELD_FAITH'),
    ('ASAI_DEITY_INFORMATION_FAITH', 'Amount', 0),
    ('ASAI_DEITY_INFORMATION_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
    ('ASAI_DEITY_INFORMATION_PRODUCTION', 'Amount', 10),
    ('ASAI_DEITY_INFORMATION_GOLD', 'YieldType', 'YIELD_GOLD'),
    ('ASAI_DEITY_INFORMATION_GOLD', 'Amount', 10);

-- Remove the pre-0.9 combat step before replacing it with the Medieval step.
DELETE FROM TraitModifiers
WHERE ModifierId = 'ASAI_DEITY_MODERN_COMBAT';

DELETE FROM ModifierArguments
WHERE ModifierId = 'ASAI_DEITY_MODERN_COMBAT';

DELETE FROM Modifiers
WHERE ModifierId = 'ASAI_DEITY_MODERN_COMBAT';

-- Combat and experience bonuses also ramp instead of peaking on turn one.
INSERT OR IGNORE INTO Modifiers
    (ModifierId, ModifierType, OwnerRequirementSetId)
VALUES
    ('ASAI_DEITY_OPENING_COMBAT', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_DIFFICULTY', 'ASAI_DEITY_AI'),
    ('ASAI_DEITY_MEDIEVAL_COMBAT', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_DIFFICULTY', 'ASAI_DEITY_AI_MEDIEVAL'),
    ('ASAI_DEITY_RENAISSANCE_COMBAT', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_DIFFICULTY', 'ASAI_DEITY_AI_RENAISSANCE'),
    ('ASAI_DEITY_OPENING_XP', 'MODIFIER_PLAYER_UNITS_ADJUST_UNIT_EXPERIENCE_MODIFIER', 'ASAI_DEITY_AI'),
    ('ASAI_DEITY_CLASSICAL_XP', 'MODIFIER_PLAYER_UNITS_ADJUST_UNIT_EXPERIENCE_MODIFIER', 'ASAI_DEITY_AI_CLASSICAL'),
    ('ASAI_DEITY_MEDIEVAL_XP', 'MODIFIER_PLAYER_UNITS_ADJUST_UNIT_EXPERIENCE_MODIFIER', 'ASAI_DEITY_AI_MEDIEVAL'),
    ('ASAI_DEITY_RENAISSANCE_XP', 'MODIFIER_PLAYER_UNITS_ADJUST_UNIT_EXPERIENCE_MODIFIER', 'ASAI_DEITY_AI_RENAISSANCE'),
    ('ASAI_DEITY_INDUSTRIAL_XP', 'MODIFIER_PLAYER_UNITS_ADJUST_UNIT_EXPERIENCE_MODIFIER', 'ASAI_DEITY_AI_INDUSTRIAL'),
    ('ASAI_DEITY_MODERN_XP', 'MODIFIER_PLAYER_UNITS_ADJUST_UNIT_EXPERIENCE_MODIFIER', 'ASAI_DEITY_AI_MODERN'),
    ('ASAI_DEITY_ATOMIC_XP', 'MODIFIER_PLAYER_UNITS_ADJUST_UNIT_EXPERIENCE_MODIFIER', 'ASAI_DEITY_AI_ATOMIC');

INSERT OR REPLACE INTO ModifierArguments
    (ModifierId, Name, Value)
VALUES
    ('ASAI_DEITY_OPENING_COMBAT', 'Amount', -1),
    ('ASAI_DEITY_MEDIEVAL_COMBAT', 'Amount', 1),
    ('ASAI_DEITY_RENAISSANCE_COMBAT', 'Amount', 1),
    ('ASAI_DEITY_OPENING_XP', 'Amount', -10),
    ('ASAI_DEITY_CLASSICAL_XP', 'Amount', 2),
    ('ASAI_DEITY_MEDIEVAL_XP', 'Amount', 2),
    ('ASAI_DEITY_RENAISSANCE_XP', 'Amount', 2),
    ('ASAI_DEITY_INDUSTRIAL_XP', 'Amount', 2),
    ('ASAI_DEITY_MODERN_XP', 'Amount', 2),
    ('ASAI_DEITY_ATOMIC_XP', 'Amount', 0);

INSERT OR IGNORE INTO TraitModifiers
    (TraitType, ModifierId)
SELECT 'TRAIT_LEADER_MAJOR_CIV', ModifierId
FROM Modifiers
WHERE ModifierId LIKE 'ASAI_DEITY_%';
