-- High-value global corrections. These values affect AI valuation, not yields.
UPDATE PseudoYields
SET DefaultValue = MAX(DefaultValue, 4.0)
WHERE PseudoYieldType = 'PSEUDOYIELD_IMPROVEMENT';

UPDATE PseudoYields
SET DefaultValue = MAX(DefaultValue, 4.0)
WHERE PseudoYieldType = 'PSEUDOYIELD_UNIT_TRADE';

UPDATE PseudoYields
SET DefaultValue = MAX(DefaultValue, 4.0)
WHERE PseudoYieldType = 'PSEUDOYIELD_UNIT_AIR_COMBAT';

-- Reserve gold for upgrades and purchases before leaving it in the slush fund.
UPDATE AiFavoredItems SET Value = 1
WHERE ListType = 'DefaultSavings' AND Item = 'SAVING_GREAT_PEOPLE';
UPDATE AiFavoredItems SET Value = 2
WHERE ListType = 'DefaultSavings' AND Item = 'SAVING_UNITS';
UPDATE AiFavoredItems SET Value = 3
WHERE ListType = 'DefaultSavings' AND Item = 'SAVING_PLOTS';
UPDATE AiFavoredItems SET Value = 4
WHERE ListType = 'DefaultSavings' AND Item = 'SAVING_SLUSH_FUND';

-- Production remains the universal bottleneck, but science and culture must not
-- be neglected after the opening expansion phase.
UPDATE AiFavoredItems SET Value = 22
WHERE ListType = 'DefaultYieldBias' AND Item = 'YIELD_PRODUCTION';
UPDATE AiFavoredItems SET Value = 14
WHERE ListType = 'DefaultYieldBias' AND Item = 'YIELD_SCIENCE';
UPDATE AiFavoredItems SET Value = 14
WHERE ListType = 'DefaultYieldBias' AND Item = 'YIELD_CULTURE';
UPDATE AiFavoredItems SET Value = 16
WHERE ListType = 'DefaultYieldBias' AND Item = 'YIELD_GOLD';

-- Defaults used by the gameplay script and the optional metrics logger.
DELETE FROM GlobalParameters
WHERE Name IN (
    'ASAI_METRICS_INTERVAL',
    'ASAI_INFRA_START_TURN',
    'ASAI_RELATIVE_START_TURN',
    'ASAI_RELATIVE_CHECK_INTERVAL',
    'ASAI_RELATIVE_TRAILING_ENTER_X100',
    'ASAI_RELATIVE_TRAILING_EXIT_X100',
    'ASAI_RELATIVE_LEADING_EXIT_X100',
    'ASAI_RELATIVE_LEADING_ENTER_X100',
    'ASAI_RELATIVE_LEADING_PILLAR_MIN_X100'
);

INSERT OR REPLACE INTO GlobalParameters (Name, Value) VALUES
    ('ASAI_VERSION', '0.8.0'),
    ('ASAI_ENABLE_METRICS', 1),
    ('ASAI_OPENING_EXPANSION_END_STANDARD', 70),
    ('ASAI_OPENING_EXPANSION_CITY_TARGET', 3),
    ('ASAI_INFRA_START_TURN_STANDARD', 20),
    ('ASAI_INFRA_IMPROVEMENTS_PER_CITY_X100', 200),
    ('ASAI_INFRA_IMPROVEMENTS_PER_POP_X100', 65),
    ('ASAI_INFRA_OWNED_PLOTS_CAP_X100', 30),
    ('ASAI_INFRA_BUILDER_CREDIT', 2),
    ('ASAI_EXPANSION_CITIES_PER_INFLIGHT_SETTLER', 5),
    ('ASAI_TRADE_CAPACITY_START_STANDARD', 35),
    ('ASAI_TRADE_CITIES_PER_CAPACITY', 3),
    ('ASAI_GOLD_RESERVE_PER_CITY', 15),
    ('ASAI_WAR_FRONT_CITY_DISTANCE', 12),
    ('ASAI_WAR_RECENT_COMBAT_STANDARD', 8),
    ('ASAI_WAR_COMBAT_ATTRIBUTION_DISTANCE', 4),
    ('ASAI_RELATIVE_PACING_ENABLED', 1),
    ('ASAI_RELATIVE_START_TURN_STANDARD', 35),
    ('ASAI_RELATIVE_CHECK_INTERVAL_STANDARD', 4),
    ('ASAI_RELATIVE_MIN_DWELL_STANDARD', 12),
    ('ASAI_RELATIVE_COOLDOWN_STANDARD', 8),
    ('ASAI_RELATIVE_CONFIRM_SAMPLES', 2),
    ('ASAI_RELATIVE_EMA_ALPHA_X100', 35),
    ('ASAI_RELATIVE_FOCUS_SWITCH_MARGIN_X100', 12),
    ('ASAI_RELATIVE_FOCUS_REVIEW_STANDARD', 12),
    ('ASAI_RELATIVE_FOCUS_MIN_GAIN_X100', 3),
    ('ASAI_RELATIVE_FOCUS_RAW_MIN_GAIN_X100', 1),
    ('ASAI_RELATIVE_FOCUS_STALL_LIMIT', 3),
    ('ASAI_RELATIVE_FOCUS_STALL_COOLDOWN_STANDARD', 16),
    ('ASAI_RELATIVE_SEVERE_ENTER_X100', 80),
    ('ASAI_RELATIVE_SEVERE_EXIT_X100', 88),
    ('ASAI_RELATIVE_SEVERE_CORE_ENTER_X100', 78),
    ('ASAI_RELATIVE_SEVERE_CORE_EXIT_X100', 86),
    ('ASAI_RELATIVE_EARLY_TRAILING_ENTER_X100', 88),
    ('ASAI_RELATIVE_EARLY_TRAILING_EXIT_X100', 94),
    ('ASAI_RELATIVE_EARLY_LEADING_EXIT_X100', 118),
    ('ASAI_RELATIVE_EARLY_LEADING_ENTER_X100', 125),
    ('ASAI_RELATIVE_EARLY_LEADING_PILLAR_MIN_X100', 80),
    ('ASAI_RELATIVE_MID_TRAILING_ENTER_X100', 90),
    ('ASAI_RELATIVE_MID_TRAILING_EXIT_X100', 96),
    ('ASAI_RELATIVE_MID_LEADING_EXIT_X100', 113),
    ('ASAI_RELATIVE_MID_LEADING_ENTER_X100', 120),
    ('ASAI_RELATIVE_MID_LEADING_PILLAR_MIN_X100', 85),
    ('ASAI_RELATIVE_LATE_TRAILING_ENTER_X100', 92),
    ('ASAI_RELATIVE_LATE_TRAILING_EXIT_X100', 97),
    ('ASAI_RELATIVE_LATE_LEADING_EXIT_X100', 108),
    ('ASAI_RELATIVE_LATE_LEADING_ENTER_X100', 115),
    ('ASAI_RELATIVE_LATE_LEADING_PILLAR_MIN_X100', 90),
    ('ASAI_RELATIVE_COMPONENT_MIN_X100', 55),
    ('ASAI_RELATIVE_COMPONENT_MAX_X100', 145),
    ('ASAI_RELATIVE_MILITARY_MAX_X100', 120),
    ('ASAI_RELATIVE_SCIENCE_ENTER_X100', 88),
    ('ASAI_RELATIVE_SCIENCE_EXIT_X100', 96),
    ('ASAI_RELATIVE_CULTURE_ENTER_X100', 85),
    ('ASAI_RELATIVE_CULTURE_EXIT_X100', 95),
    ('ASAI_RELATIVE_EMPIRE_ENTER_X100', 85),
    ('ASAI_RELATIVE_EMPIRE_EXIT_X100', 95),
    ('ASAI_RELATIVE_WEIGHT_TECHS', 20),
    ('ASAI_RELATIVE_WEIGHT_CIVICS', 18),
    ('ASAI_RELATIVE_WEIGHT_SCIENCE', 12),
    ('ASAI_RELATIVE_WEIGHT_CULTURE', 12),
    ('ASAI_RELATIVE_WEIGHT_CITIES', 10),
    ('ASAI_RELATIVE_WEIGHT_POPULATION', 15),
    ('ASAI_RELATIVE_WEIGHT_MILITARY', 13);
